/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        arial: ['Arial', 'sans-serif'],
        barlow: ['Barlow', 'sans-serif'],
        calibri: ['Calibri', 'sans-serif'],
        courierNew: ['Courier New', 'monospace'],
        crimsonText: ['Crimson Text', 'serif'],
        ebGaramond: ['EB Garamond', 'serif'],
        exo2: ['Exo 2', 'sans-serif'],
        firaSans: ['Fira Sans', 'sans-serif'],
        futura: ['Futura', 'sans-serif'],
        garamond: ['Garamond', 'serif'],
        georgia: ['Georgia', 'serif'],
        helvetica: ['Helvetica', 'sans-serif'],
        ibmPlexSans: ['IBM Plex Sans', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        inconsolata: ['Inconsolata', 'monospace'],
        josefinSans: ['Josefin Sans', 'sans-serif'],
        kanit: ['Kanit', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        libreBaskerville: ['Libre Baskerville', 'serif'],
        lora: ['Lora', 'serif'],
        lucidaConsole: ['Lucida Console', 'monospace'],
        merriweather: ['Merriweather', 'serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        nunito: ['Nunito', 'sans-serif'],
        nunitoSans: ['Nunito Sans', 'sans-serif'],
        openSans: ['Open Sans', 'sans-serif'],
        oswald: ['Oswald', 'sans-serif'],
        palanquin: ['Palanquin', 'sans-serif'],
        play: ['Play', 'sans-serif'],
        playfair: ['Playfair', 'serif'],
        poppins: ['Poppins', 'sans-serif'],
        ptSans: ['PT Sans', 'sans-serif'],
        ptSerif: ['PT Serif', 'serif'],
        quicksand: ['Quicksand', 'sans-serif'],
        raleway: ['Raleway', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        rubik: ['Rubik', 'sans-serif'],
        sourceCodePro: ['Source Code Pro', 'monospace'],
        sourceSansPro: ['Source Sans Pro', 'sans-serif'],
        timesNewRoman: ['Times New Roman', 'serif'],
        titilliumWeb: ['Titillium Web', 'sans-serif'],
        ubuntu: ['Ubuntu', 'sans-serif'],
        verdana: ['Verdana', 'sans-serif'],
        workSans: ['Work Sans', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}